
```typescript
try {
  throw new Error("unexpected error");
} catch (error) {
  span.end({
    error: error,
  });
}
```